apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"long-load"},"name":"long-load","namespace":"test-ha"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"long-load"}},"strategy":{},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"long-load"}},"spec":{"containers":[{"image":"quay.io/anwarfouad/long-load","name":"long-load","resources":{}}]}}},"status":{}}
  creationTimestamp: "2025-01-29T08:16:21Z"
  generation: 6
  labels:
    app: long-load
  name: long-load
  namespace: test-ha
  resourceVersion: "114514"
  uid: 22cabc93-226e-4baf-8f19-27aca9aa3c68
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: long-load
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: long-load
    spec:
      containers:
      - image: quay.io/anwarfouad/long-load
        imagePullPolicy: Always
        name: long-load
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /health
            port: 3000
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3000
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-01-29T08:16:30Z"
    lastUpdateTime: "2025-01-29T08:16:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-01-29T08:16:21Z"
    lastUpdateTime: "2025-01-29T08:30:56Z"
    message: ReplicaSet "long-load-64b77f8c9d" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
