apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"php-ssl:1"},"fieldPath":"spec.template.spec.containers[?(@.name==\"php-ssl\")].image"}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"app2"},"name":"app2","namespace":"updates-review"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"app2"}},"template":{"metadata":{"labels":{"app":"app2"}},"spec":{"containers":[{"command":["sleep","365d"],"image":"php-ssl:1","name":"php-ssl"}]}}}}
  creationTimestamp: "2025-01-29T18:12:06Z"
  generation: 3
  labels:
    app: app2
  name: app2
  namespace: updates-review
  resourceVersion: "154272"
  uid: d2ba26cf-18c2-42dd-91eb-e97ef6aad041
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: app2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app2
    spec:
      containers:
      - command:
        - sleep
        - 365d
        image: registry.ocp4.example.com:8443/redhattraining/php-ssl@sha256:9fa4dfc5c6f7fa96eeb4521ffe4959d0e212ca02c0b7488aa71b8b3c84dffce4
        imagePullPolicy: IfNotPresent
        name: php-ssl
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-01-29T18:12:19Z"
    lastUpdateTime: "2025-01-29T18:12:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-01-29T18:12:06Z"
    lastUpdateTime: "2025-01-29T18:16:30Z"
    message: ReplicaSet "app2-8564f6cf78" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
